<?php
/** @var UsuarioController $this */

?>
<html>
<head>
<title><?= APP_TITLE; ?></title>
<style type="text/css">
<?php Html::doLoadCSS('styles'); ?>
</style>
<script type="text/javascript">

var IMAGE_PATH      = "<?= IMAGE_PATH; ?>";
var SERVLET_PREFFIX = "<?= $this->getServletPath(); ?>";
var SERVLET_PATH    = "<?= $this->getServletPath(''); ?>";
var SERVLET_ACTION  = "<?= $this->getServletAction(''); ?>";

</script>
<?php Html::doLoadJS(); ?>
</head>
<body>
<img style="position:absolute; width:100%; height:100%;" src="<?= Html::getImagePath('linux_fedora8_bg.png'); ?>" />
<div style="position:absolute; width:100%; height:100%;" id="div_pagina">
<table width="100%" height="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td height="57">
      <table width="100%" cellpadding="0" cellspacing="0">
		<tr>
		  <td width="65"><?= Html::getImage('mac.panel.top.left.png'); ?></td>
		  <td style="background:url(<?= Html::getImagePath('mac.panel.top.middle.png'); ?>);">
		    <table width="99%" align="center" cellpadding="0" cellspacing="0">
		      <tr>
		        <td height="24" align="center">&nbsp;</td>
		      </tr>
		      <tr>
		        <td height="33" align="center"><?= getInfo(); ?></td>
		      </tr>
		    </table>
		  </td>
		  <td width="30"><?= Html::getImage('mac.panel.top.right.png', array('style' => 'cursor:pointer;', 'onclick' => sprintf("location = '%s';", $this->getServletPath('logoff')))); ?></td>
		</tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="100%" style="background:rgb(232, 232, 232);" valign="top">
	<?php
	
		echo '<table cellpadding="0" cellspacing="0"><tr>';
	
		if (APP_CURR_NAVIGATOR == 'left') {
			echo '<td>';
			echo $this->getView('navigator');
			echo '</td>';
			echo '<td class="esquerda">';
			echo $this->getView('workspaces');
			echo '</td>';
		}
		else {
			echo '<td>';
			echo $this->getView('workspaces');
			echo '</td>';
			echo '<td class="esquerda">';
			echo $this->getView('navigator');
			echo '</td>';
		}
		
		echo '</tr></table>';
		
	?>
    </td>
  </tr>
  <tr>
    <td height="20">
	  <table width="100%" cellpadding="0" cellspacing="0">
		<tr>
		  <td width="25"><?= Html::getImage('mac.panel.bottom.left.png'); ?></td>
		  <td style="background:url(<?= Html::getImagePath('mac.panel.bottom.middle.png'); ?>);">
		    <div align="center">
		      <?php printf('Copyright &copy; 2012 (P) %s - %s. All rights reserved.', date('Y'), APP_TITLE); ?>
		    </div>
		  </td>
		  <td width="16"><?= Html::getImage('mac.panel.bottom.right.png'); ?></td>
		</tr>
      </table>
    </td>
  </tr>
</table>
</div>
<?= $this->getView('modal'); ?>
<script type="text/javascript">

window.onresize = function () {
	doResize();
};

doResize();
Util.$$("div_pagina").show();

</script>
<noscript>
<div style="position:absolute;" class="white_title">Javascript desabilitado. Favor, habilite-o no seu navegador e tente novamente!</div>
</noscript>
</body>
</html>