<?php

$users      = CollectionUsuario::retrieve();
$auth_user  = Request::getAttribute('auth_user', true);
$message    = Request::getAttribute('message', true);

$campo      = $auth_user ? 'password' : 'username';
$type       = $campo == 'username' ? 'text' : 'password';

?>
<html>
<head>
<title><?= APP_TITLE; ?></title>
<style type="text/css">
<?php Html::doLoadCSS('styles', 'logon'); ?>
</style>
<?php Html::doLoadJS('v2.0a/PHP', 'v2.0a/Util'); ?>
<script type="text/javascript">

function doResize() {
	Util.$$("div_logon").center(632, 479);
}

</script>
</head>
<body>
<img style="position:absolute; width:100%; height:100%;" src="<?= getPath(IMAGE_PATH, 'linux/linux.fedora8.bg.png'); ?>" />
<div style="position:absolute;" id="div_logon">
  <form id="frm" method="post" action="<?= Request::getServletPath('logon'); ?>">
  <?php echo ($type == 'password' ? Html::hidden('username', $auth_user) : ''); ?>
  <table width="100%">
    <tr>
      <td width="279" class="white_title"><?php echo 'Welcome ', $auth_user; ?></td>
      <td width="14" rowspan="3">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>
        <div align="right" class="blue_text">
          <?= getInfo(); ?>
        </div>
      </td>
    </tr>
    <tr>
      <td valign="top">
        <div style="padding-left:6px; padding-right:6px;">
        <?php

        echo '<table width="100%">';

        while ($linha = $users->next()) {
			echo PString::format('<tr><td width="50"><img src="{0}" /></td><td><div class="{2}" onclick="Util.$$(\'username\').val(\'{1}\'); document.getElementById(\'frm\').submit();">{1}</div></td></tr>', getPath(IMAGE_PATH, 'linux/linux.user.png'), $linha->getUsername(), ($linha->getUsername() == $auth_user ? 'selected' : 'hover'));
		}

		echo '</table>';

        ?>
        </div>
      </td>
      <td valign="top">
        <div style="padding-left:6px; padding-right:6px;">
          <?= Html::spacer(12); ?>
          <?= Html::getTextField($type, $campo, '', null, '100%', 20, false, "if (Util.isEnter(event)) {this.form.submit();}"); ?>
          <?= Html::spacer(28); ?>
          <div class="blue_text" align="center"><?= $message; ?>&nbsp;</div>
          <?= Html::spacer(88); ?>
          <div class="hover" align="center" onclick="alert('Em desenvolvimento!');">&nbsp;</div>
          <?= Html::spacer(6); ?>
          <div class="hover" align="center" onclick="alert('Em desenvolvimento!');">&nbsp;</div>
          <?= Html::spacer(13); ?>
          <div class="hover" align="center" onclick="location = '<?= Request::getServletPath('logon'); ?>';">&nbsp;</div>
        </div>
      </td>
    </tr>
  </table>
  </form>
</div>
<script>

window.onresize = function () {
	doResize();
};

doResize();
Util.$$("<?= $campo; ?>").focus();

</script>
</body>
</html>